


cache/glass_od.metadata.patients__step_001.Rds cache/glass_od.metadata.resections__step_001.Rds cache/glass_od.metadata.array_samples__step_001.Rds:
	echo "step 001"



cache/glass_od.metadata.array_samples.Rds:
	echo "AAA" > cache/glass_od.metadata.array_samples.Rds  # Rscript --vanilla scripts/load_GLASS-OD_metadata__step_001.R



all: cache/glass_od.metadata.array_samples.Rds
