#!/usr/bin/env R


CONST_N_PROBES <- 865859
CONST_N_PROBES_UNMASKED <- 760405
CONST_N_PROBES_UNMASKED_AND_DETP <- 691380


CONST_N_GLASS_OD_ALL_SAMPLES   <- 274
CONST_N_VALIDATION_ALL_SAMPLES <- 1 + 57 # 1 non pair plus oligosarcoma paper


CONST_N_GLASS_OD_INCLUDED_SAMPLES <- 209
CONST_N_OD_VALIDATION_INCLUDED_SAMPLES <- CONST_N_VALIDATION_ALL_SAMPLES - 34
CONST_N_GLASS_NL_INCLUDED_SAMPLES <- 218
CONST_N_GSAM_INCLUDED_SAMPLES <- 77


CONST_N_SAMPLES <- CONST_N_GLASS_OD_INCLUDED_SAMPLES +
  CONST_N_OD_VALIDATION_INCLUDED_SAMPLES +
  CONST_N_GLASS_NL_INCLUDED_SAMPLES +
  CONST_N_GSAM_INCLUDED_SAMPLES


