#!/usr/bin/env R 


if (!exists("glass_od.metadata.idats")) {
  source("scripts/load_metadata.R")
}



# GLASS-OD ----

## load m-values [as generated by analysis_mvalues.R ] ----


glass_od.data.mvalues <- readRDS("cache/mvalues.Rds") |> # already filtered at probe level, not at patient level [except those that were discarded for database reasons]
  (function(.) {
    print(dim(.)) # has had detP filtering already
    assertthat::assert_that(all(colnames(.) %in% glass_od.metadata.idats$sentrix_id))
    return(.)
  })()


glass_od.data.mvalues.mask <- readRDS("cache/mvalues_detP_mask.Rds") |> 
  (function(.) {
    print(dim(.)) # has had detP filtering already
    assertthat::assert_that(all(colnames(.) == colnames(glass_od.data.mvalues)))
    return(.)
  })() |> 
  (function(.) {
    assertthat::assert_that(all(rownames(.) == rownames(glass_od.data.mvalues)))
    return(.)
  })()





# GLASS-NL ----


glass_nl.data.mvalues <- readRDS('/home/r361003/mnt/neuro-genomic-1-ro/glass/Methylation/Analysis/RDA_files/BetaValues_procNoob_09052022.rds') |> 
  as.data.frame(stringsAsFactors=F) |> 
  dplyr::select(glass_nl.metadata.resections |> dplyr::filter(!is.na(methylation.sid)) |>  dplyr::pull(methylation.sid))  |> 
  (function(.) {
    print(dim(.)) # has had detP filtering already
    assertthat::assert_that(sum(is.na(.)) == 0)
    return(.)
  })()





