#!/usr/bin/env R 


if(!exists("glass_od.metadata.idats")) {
  source('scripts/load_metadata.R')
}


# load m-values [as generated by analysis_unsupervised_qc.R ] ----

glass_od.mvalues <- readRDS('cache/mvalues.Rds') |>  # already filtered at probe level, not at patient level [except those that were discarded for database reasons]
  tibble::column_to_rownames('probeID')



# sample (sub) selection ----

pca.raw <- readRDS("cache/analysis_supervised_qc_pca.Rds") |> 
  purrr::pluck('x')  |>   # take coordinates
  as.data.frame(stringsAsFactor=F) |> 
  dplyr::filter(PC1 > 60) |> 
  tibble::rownames_to_column('sentrix_id') |> 
  dplyr::pull(sentrix_id)

# [1] "203989100035_R08C01" "203989100149_R03C01" "203991400003_R07C01" "203991400003_R08C01" "204074220048_R02C01" "204787070003_R07C01"
# [7] "204787070018_R05C01" "204787070018_R06C01" "206467010147_R02C01" "206467010147_R03C01" "206467010147_R06C01" "206116800026_R05C01"
# [13] "206116800026_R07C01" "206116800056_R02C01" "206116800056_R04C01" "206137490053_R02C01" "206137490053_R03C01" "206137490053_R04C01"
# [19] "206137490053_R05C01" "206137490057_R01C01" "206137490109_R07C01" "206467010068_R03C01" "206467010068_R05C01" "206467010175_R01C01"


exclude <- glass_od.metadata.idats |> 
  
  dplyr::filter(is.na(reason_excluded_patient)) |> 
  dplyr::filter(is.na(reason_excluded_resection)) |> 
  dplyr::filter(is.na(reason_excluded_resection_isolation)) |> 
  dplyr::filter(is.na(reason_excluded_array_sample)) |> 

  dplyr::mutate(exclude = ifelse(percentage.detP.signi > 5, T, F)) |> 
  dplyr::mutate(exclude = ifelse(sentrix_id %in% pca.raw, T, exclude)) |> 
  dplyr::filter(exclude) |> 
  dplyr::pull(sentrix_id)


stopifnot(ncol(glass_od.mvalues) == 204)

glass_od.mvalues <- glass_od.mvalues |> 
  dplyr::select(-any_of(exclude))

# exclude[exclude %in% colnames(glass_od.mvalues)== F]

stopifnot(ncol(glass_od.mvalues) < 204)

rm(exclude, pca.raw)

