#!/usr/bin/env R 


if (!exists("glass_od.metadata.idats")) {
  source("scripts/load_metadata.R")
}


# load m-values [as generated by analysis_mvalues.R ] ----


glass_od.data.mvalues <- readRDS("cache/mvalues.Rds") |> # already filtered at probe level, not at patient level [except those that were discarded for database reasons]
  tibble::column_to_rownames("probeID")

stopifnot(colnames(glass_od.data.mvalues) %in% glass_od.metadata.idats$sentrix_id)

